### ISSUE TITLE
feat: EmbeddingsBuilder redesign

### ISSUE THREAD

**Issue by garance-buricatu** [0xPlaygrounds/rig#52]
## Feature Request
Any object that implements the trait `Embedabble` can be added to the embeddings builder and therefore can be embedded.

### Motivation
Currently, embeddings builder is tightly coupled with the `DocumentEmbedding` type (only objects of this type can be used by the builder). **Downsides**: user needs to type cast their types to `DocumentEmbedding` and the structure of `DocumentEmbedding` is predetermined so the user needs to design their embedding code around this.

### Proposal
1. Define the trait `Embedabble` which contains a method `fn embedabble()` which returns a list of strings (the strings that should be embedded).
2. Change the `EmbeddingsBuilder` to accept any type that implements the trait `Embedabble`.
3. Write a custom derive macro that can be used on any struct which derives the `Embedabble` trait automatically.

### Linked issues:
#60 
#61
#62

#### Todo:

- [x] Give trait and macro same name like serde

- [x] implement Embeddable trait for many primitive types

- [x] macro fails when there are no embed tags

- [x] macro fails when embed with is empty string

- [x] need to handle error in custom embed function

- [x] review borrow and owning eveywhere. **done for embeddings.rs**

- [x] update docstrings. **done for embeddings.rs**

- [ ] clean up embedding builder definition with traits maybe?

- [x] should build() return `Embedding` object or just string? **return `Embedding` object - document string used for debugging**

- [ ] in memory vector store, rethink type of document D --> move to another branch

- [x] why is vector search of in memory vector store so bad? **bug found**

- [ ] in memory store - implement from trait from both returns types of build into add_document
- [x]  tests
- [x] make macro as feature flag

**Comment by cvauclair** [comment]
@garance-buricatu can you add some formatting and a little bit more context to this issue? Thank you!
